name: directory-listing
on: workflow_dispatch

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Directory Listings Index
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: simple

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #  output to publish to the `gh-pages` branch:
          publish_dir: ./simple
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
  
